# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: db-container
          image: 032566931471.dkr.ecr.us-east-1.amazonaws.com/db-repo:v0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password1234
            - name: MYSQL_DATABASE
              value: employees
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: secret-registry
