apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: 032566931471.dkr.ecr.us-east-1.amazonaws.com/db-repo:v0.1
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: Password1234
        ports:
        - containerPort: 3306
      imagePullSecrets:
        - name: secret-registry
