apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: db-container
      image: 032566931471.dkr.ecr.us-east-1.amazonaws.com/db-repo:v0.1
      env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: employees
      ports:
        - containerPort: 3306
          protocol: TCP 
  imagePullSecrets:
    - name: secret-registry
