apiVersion: v1
kind: Pod
metadata:
  name: employees
  labels:
    app: employees
spec:
  containers:
  - name: app-container
    image: 032566931471.dkr.ecr.us-east-1.amazonaws.com/app-repo:v0.1
    env:
    - name: DBHOST
      value: mysql.database.svc.cluster.local 
    - name: DBUSER
      value: root
    - name: DBPWD
      value: password1234
    - name: DATABASE
      value: employees
    - name: DBPORT
      value: "3306"
    - name: APP_COLOR
      value: pink
    ports:
    - containerPort: 8080
      protocol: TCP
  imagePullSecrets:
    - name: secret-registry