# web-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeesgreen
  labels:
    app: employeesgreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeesgreen
  template:
    metadata:
      name: employeesgreen
      namespace: application
      labels:
        app: employeesgreen
    spec:
      containers:
      - name: appgreen-container
        image: 032566931471.dkr.ecr.us-east-1.amazonaws.com/app-repo:v0.1
        env:
          - name: DBHOST
            value: mysql.database.svc.cluster.local
          - name: DBUSER
            value: root
          - name: DATABASE
            value: employeesgreen
          - name: DBPWD
            value: Password1234
          - name: DBPORT
            value: "3306"
          - name: APP_COLOR
            value: green
        ports:
          - containerPort: 8080
      imagePull  imagePullSecrets:
        - name: secret-registry